DROP TABLE IF EXISTS DISCOVERED_HOST;
DROP TABLE IF EXISTS HOST_SCAN_HISTORY;
DROP TABLE IF EXISTS SETTING;

CREATE TABLE DISCOVERED_HOST
(
	IP_ADDRESS           VARCHAR(100) NOT NULL COMMENT '아이피 주소',
	SCAN_HISTORY_ID      BIGINT NOT NULL COMMENT '스캔내역 아이디',
	REPLY_TTL            INTEGER NULL COMMENT '응답 패킷 TTL',
	OS_NAME              VARCHAR(20) NULL COMMENT '운영체체',
	DISCOVERED_DATETIME  DATETIME NULL COMMENT '발견일시',
	PRIMARY KEY (IP_ADDRESS,SCAN_HISTORY_ID)
);

CREATE INDEX _DISCOVERED_HOST_1 ON DISCOVERED_HOST
(
	SCAN_HISTORY_ID
);

CREATE TABLE HOST_SCAN_HISTORY
(
	SCAN_HISTORY_ID      BIGINT NOT NULL AUTO_INCREMENT COMMENT '스캔내역 아이디',
	CIDR                 VARCHAR(20) NULL COMMENT 'CIDR',
	SCAN_START_DATETIME  DATETIME NULL COMMENT '스캔 시작일시',
	SCAN_END_DATETIME    DATETIME NULL COMMENT '스캔 종료일시',
	DELETE_YN            VARCHAR(1) NOT NULL COMMENT '삭제 여부',
	DISCOVERED_HOST_COUNT INTEGER NULL COMMENT '발견된 호스트 갯수',
	PROJECT_ID           BIGINT NULL COMMENT '프로젝_아이디',
	COMPLETED_YN          VARCHAR(1) NOT NULL COMMENT '완료 여부',
	PRIMARY KEY (SCAN_HISTORY_ID)
);

CREATE INDEX _HOST_SCAN_HISTORY_1 ON HOST_SCAN_HISTORY
(
	PROJECT_ID
);

CREATE TABLE SETTING
(
	SETTING_ID 			BIGINT AUTO_INCREMENT COMMENT '설정 아이디',
	PARENT_SETTING_ID 	BIGINT NULL COMMENT '부모 설정 아이디',
	CATEGORY_NAME 		VARCHAR(100) NOT NULL COMMENT '카테고리명',
	PROPERTY_NAME 		VARCHAR(100) NULL COMMENT '속성이름',
	PROPERTY_VALUE 		VARCHAR(500) NULL COMMENT '속성값',
	READ_ONLY_YN 		VARCHAR(1) NULL COMMENT '읽기전용여부',
	DATA_TYPE 			VARCHAR(100) NULL COMMENT '데이터 유형',
	DATA_VALUES         VARCHAR(100) NULL COMMENT '데이터 값',
	PLACEHOLDER_ENG     VARCHAR(100) NULL COMMENT 'Placeholder 영어',
	PLACEHOLDER_KOR     VARCHAR(100) NULL COMMENT 'Placeholder 한글',
	DISPLAY_ORDER 		BIGINT NULL COMMENT '표시순서',
	REGIST_USER_ID 		BIGINT NOT NULL COMMENT '등록자',
	REGIST_DATETIME 	DATETIME NOT NULL COMMENT '등록일시',
	MODIFY_USER_ID 		BIGINT NOT NULL COMMENT '수정자',
	MODIFY_DATETIME 	DATETIME NOT NULL COMMENT '수정일시',
	PRIMARY KEY (SETTING_ID)
);

ALTER TABLE INVENTORY_MASTER MODIFY CUSTOMER_INVENTORY_CODE VARCHAR(100) NULL COMMENT '고객_인벤토리_코드';

INSERT INTO CODE_DETAIL(DOMAIN_CODE, COMMON_CODE, CODE_NAME_KOREAN, CODE_NAME_ENGLISH, CODE_DISPLAY_NUMBER, CODE_VALID_YN) VALUES (1002, 'RANGE', '아이피 범위 검색', 'Discovery IP Range', 4, 'Y');
INSERT INTO CODE_DETAIL(DOMAIN_CODE, COMMON_CODE, CODE_NAME_KOREAN, CODE_NAME_ENGLISH, CODE_DISPLAY_NUMBER, CODE_VALID_YN) VALUES (1003,'NS','지원되지 않음','Not Supported',7,'Y');
INSERT INTO CODE_DETAIL(DOMAIN_CODE, COMMON_CODE, CODE_NAME_KOREAN, CODE_NAME_ENGLISH, CODE_DISPLAY_NUMBER, CODE_VALID_YN) VALUES (1013,'JBOSS','제이보스','JBoss',23,'Y');
INSERT INTO CODE_DOMAIN_REFERENCE_DETAIL(DOMAIN_CODE, COMMON_CODE, REFERENCE_DOMAIN_CODE, REFERENCE_COMMON_CODE) VALUES (1013,'JBOSS',1001,'MW');

UPDATE CODE_DETAIL SET CODE_NAME_KOREAN = '요청됨', CODE_NAME_ENGLISH = 'Requested' WHERE DOMAIN_CODE = 1003 AND COMMON_CODE = 'REQ';
UPDATE CODE_DETAIL SET CODE_NAME_KOREAN = '취소됨', CODE_NAME_ENGLISH = 'Cancelled' WHERE DOMAIN_CODE = 1003 AND COMMON_CODE = 'CNCL';
UPDATE CODE_DETAIL SET CODE_NAME_KOREAN = '대기중' WHERE DOMAIN_CODE = 1003 AND COMMON_CODE = 'PEND';
UPDATE CODE_DETAIL SET CODE_NAME_KOREAN = '완료됨' WHERE DOMAIN_CODE = 1003 AND COMMON_CODE = 'CMPL';
UPDATE CODE_DETAIL SET CODE_NAME_KOREAN = '실패됨' WHERE DOMAIN_CODE = 1003 AND COMMON_CODE = 'FAIL';
UPDATE CODE_DETAIL SET CODE_NAME_KOREAN = '실패됨' WHERE DOMAIN_CODE = 1012 AND COMMON_CODE = 'FAIL';
UPDATE CODE_DETAIL SET CODE_NAME_KOREAN = '성공됨', CODE_NAME_ENGLISH = 'Succeeded' WHERE DOMAIN_CODE = 1012 AND COMMON_CODE = 'SUCC';
