ALTER TABLE SERVER_SUMMARY MODIFY MEM_SIZE INT NULL;
ALTER TABLE SERVER_SUMMARY MODIFY SWAP_SIZE INT NULL;
ALTER TABLE APPLICATION_MASTER MODIFY APPLICATION_SIZE BIGINT NOT NULL;
ALTER TABLE MIDDLEWARE_INSTANCE MODIFY JAVA_VERSION VARCHAR(200) NULL;
