-- Third party solution
DELETE
FROM DISCOVERED_THIRD_PARTY
WHERE THIRD_PARTY_SEARCH_TYPE_ID in (SELECT THIRD_PARTY_SEARCH_TYPE_ID
                                     FROM THIRD_PARTY_SEARCH_TYPE
                                              JOIN THIRD_PARTY_SOLUTION tps on THIRD_PARTY_SEARCH_TYPE.THIRD_PARTY_SOLUTION_ID = tps.THIRD_PARTY_SOLUTION_ID
                                     WHERE THIRD_PARTY_SOLUTION_NAME = 'PostgreSQL');
DELETE
FROM THIRD_PARTY_SOLUTION
WHERE THIRD_PARTY_SOLUTION_NAME = 'PostgreSQL';

DELETE
FROM THIRD_PARTY_SEARCH_TYPE
WHERE THIRD_PARTY_SOLUTION_ID = (SELECT THIRD_PARTY_SOLUTION_ID FROM THIRD_PARTY_SOLUTION WHERE THIRD_PARTY_SOLUTION_NAME = 'PostgreSQL');