#json split config
json:
  split-size: 10485760 # 1024 x 1024 x 10 (10M)
  split-map:
    MW-TOMCAT:
      - /instance/configFiles/TOMCAT_CONFIG_SERVER/contents
      - /instance/configFiles/TOMCAT_CONFIG_CONTEXT/contents
      - /instance/configFiles/TOMCAT_CONFIG_ENV/contents
      - /instance/globalResources
