
DROP TABLE IF EXISTS NODE_LABEL;



DROP TABLE IF EXISTS OBJECT_LABEL;



DROP TABLE IF EXISTS CLUSTER_IP;



DROP TABLE IF EXISTS SERVICE_PORT;



DROP TABLE IF EXISTS SELECTOR;



DROP TABLE IF EXISTS SERVICE;



DROP TABLE IF EXISTS CONTAINER_PORT;



DROP TABLE IF EXISTS CONTAINER_VOLUME;



DROP TABLE IF EXISTS POD_VOLUME;



DROP TABLE IF EXISTS OBJECT_ANNOTATION;



DROP TABLE IF EXISTS SCAN_ORIGIN;



DROP TABLE IF EXISTS NODE_ANNOTATION;



DROP TABLE IF EXISTS OBJECT_ORIGIN_JSON;



DROP TABLE IF EXISTS NAMESPACE_OBJECT_LINK;



DROP TABLE IF EXISTS NAMESPACE;



DROP TABLE IF EXISTS PROCESS_SERVICE_LINK;



DROP TABLE IF EXISTS PROCESS_EXTERNAL_CONNECT;



DROP TABLE IF EXISTS MIDDLEWARE_CONFIG;



DROP TABLE IF EXISTS MIDDLEWARE_APPLICATION_LINK;



DROP TABLE IF EXISTS CONTAINER_MIDDLEWARE;



DROP TABLE IF EXISTS CONTAINER_APPLICATION;



DROP TABLE IF EXISTS CONTAINER_DATABASE;



DROP TABLE IF EXISTS CONTAINER_PROCESS;



DROP TABLE IF EXISTS CONTAINER;



DROP TABLE IF EXISTS POD;



DROP TABLE IF EXISTS NODE;



DROP TABLE IF EXISTS INGRESS_RULE_TARGET;



DROP TABLE IF EXISTS INGRESS_RULE;



DROP TABLE IF EXISTS INGRESS;



DROP TABLE IF EXISTS OBJECT;



DROP TABLE IF EXISTS CLUSTER_SCAN;



DROP TABLE IF EXISTS K8S_CLUSTER;



CREATE TABLE CLUSTER_IP
(
    CLUSTER_IP_ID        BIGINT AUTO_INCREMENT COMMENT '',
    IP                   VARCHAR(50) NULL COMMENT '',
    OBJECT_ID            BIGINT NOT NULL COMMENT '',
    PRIMARY KEY (CLUSTER_IP_ID)
);



CREATE INDEX _CLUSTER_IP_1 ON CLUSTER_IP
    (
     OBJECT_ID
        );



CREATE TABLE CLUSTER_SCAN
(
    CLUSTER_SCAN_ID      BIGINT AUTO_INCREMENT COMMENT '',
    SCAN_STATUS          VARCHAR(100) NOT NULL COMMENT '',
    SCAN_STATUS_MESSAGE  VARCHAR(100) NULL COMMENT '',
    SERVER_VERSION       VARCHAR(100) NULL COMMENT '',
    SCAN_DATETIME        DATETIME NULL COMMENT '',
    K8S_CLUSTER_ID       BIGINT NOT NULL COMMENT '',
    PRIMARY KEY (CLUSTER_SCAN_ID)
);



CREATE INDEX _CLUSTER_SCAN_1 ON CLUSTER_SCAN
    (
     K8S_CLUSTER_ID
        );



CREATE TABLE CONTAINER
(
    CONTAINER_ID         BIGINT AUTO_INCREMENT COMMENT '',
    IMAGE                VARCHAR(100) NOT NULL COMMENT '',
    NAME                 VARCHAR(100) NOT NULL COMMENT '',
    OBJECT_ID            BIGINT NOT NULL COMMENT '',
    PRIMARY KEY (CONTAINER_ID)
);



CREATE INDEX _CONTAINER_1 ON CONTAINER
    (
     OBJECT_ID
        );



CREATE TABLE CONTAINER_APPLICATION
(
    PROCESS_ID           BIGINT NOT NULL COMMENT '',
    NAME                 VARCHAR(100) NOT NULL COMMENT '',
    PATH                 VARCHAR(500) NULL COMMENT '',
    PRIMARY KEY (PROCESS_ID)
);



CREATE UNIQUE INDEX _CONTAINER_APPLICATION_1 ON CONTAINER_APPLICATION
    (
     PROCESS_ID
        );



CREATE TABLE CONTAINER_DATABASE
(
    PROCESS_ID           BIGINT NOT NULL COMMENT '',
    NAME                 VARCHAR(100) NOT NULL COMMENT '',
    PRIMARY KEY (PROCESS_ID)
);



CREATE UNIQUE INDEX _CONTAINER_DATABASE_1 ON CONTAINER_DATABASE
    (
     PROCESS_ID
        );



CREATE TABLE CONTAINER_MIDDLEWARE
(
    PROCESS_ID           BIGINT NOT NULL COMMENT '',
    NAME                 VARCHAR(100) NOT NULL COMMENT '',
    PRIMARY KEY (PROCESS_ID)
);



CREATE UNIQUE INDEX _CONTAINER_MIDDLEWARE_1 ON CONTAINER_MIDDLEWARE
    (
     PROCESS_ID
        );



CREATE TABLE CONTAINER_PORT
(
    CONTAINER_PORT_ID    BIGINT AUTO_INCREMENT COMMENT '',
    CONTAINER_PORT       INTEGER NULL COMMENT '',
    PROTOCOL             VARCHAR(50) NULL COMMENT '',
    CONTAINER_ID         BIGINT NOT NULL COMMENT '',
    PRIMARY KEY (CONTAINER_PORT_ID)
);



CREATE INDEX _CONTAINER_PORT_1 ON CONTAINER_PORT
    (
     CONTAINER_ID
        );



CREATE TABLE CONTAINER_PROCESS
(
    PROCESS_ID           BIGINT AUTO_INCREMENT COMMENT '',
    NAME                 VARCHAR(100) NOT NULL COMMENT '',
    CONTAINER_ID         BIGINT NOT NULL COMMENT '',
    PRIMARY KEY (PROCESS_ID)
);



CREATE INDEX _CONTAINER_PROCESS_1 ON CONTAINER_PROCESS
    (
     CONTAINER_ID
        );



CREATE TABLE CONTAINER_VOLUME
(
    CONTAINER_VOLUME_ID  BIGINT AUTO_INCREMENT COMMENT '',
    MOUNT_PATH           VARCHAR(500) NULL COMMENT '',
    NAME                 VARCHAR(100) NOT NULL COMMENT '',
    CONTAINER_ID         BIGINT NOT NULL COMMENT '',
    POD_VOLUME_ID        BIGINT NULL COMMENT '',
    PRIMARY KEY (CONTAINER_VOLUME_ID)
);



CREATE INDEX _CONTAINER_VOLUME_1 ON CONTAINER_VOLUME
    (
     CONTAINER_ID
        );



CREATE INDEX _CONTAINER_VOLUME_2 ON CONTAINER_VOLUME
    (
     POD_VOLUME_ID
        );



CREATE TABLE INGRESS
(
    OBJECT_ID            BIGINT NOT NULL COMMENT '',
    CLASS_NAME           VARCHAR(100) NOT NULL COMMENT '',
    PRIMARY KEY (OBJECT_ID)
);



CREATE UNIQUE INDEX _INGRESS_1 ON INGRESS
    (
     OBJECT_ID
        );



CREATE TABLE INGRESS_RULE
(
    INGRESS_RULE_ID      BIGINT AUTO_INCREMENT COMMENT '',
    HOST                 VARCHAR(100) NULL COMMENT '',
    SECRET_NAME          VARCHAR(50) NULL COMMENT '',
    OBJECT_ID            BIGINT NOT NULL COMMENT '',
    PRIMARY KEY (INGRESS_RULE_ID)
);



CREATE INDEX _INGRESS_RULE_1 ON INGRESS_RULE
    (
     OBJECT_ID
        );



CREATE TABLE INGRESS_RULE_TARGET
(
    INGRESS_RULE_TARGET_ID BIGINT AUTO_INCREMENT COMMENT '',
    SERVICE_NAME         VARCHAR(100) NOT NULL COMMENT '',
    SERVICE_PORT_NAME    VARCHAR(100) NULL COMMENT '',
    SERVICE_PORT_NUMBER  INTEGER NULL COMMENT '',
    PATH                 VARCHAR(100) NULL COMMENT '',
    PATH_TYPE            VARCHAR(100) NOT NULL COMMENT '',
    INGRESS_RULE_ID      BIGINT NULL COMMENT '',
    PRIMARY KEY (INGRESS_RULE_TARGET_ID)
);



CREATE INDEX _INGRESS_RULE_TARGET_1 ON INGRESS_RULE_TARGET
    (
     INGRESS_RULE_ID
        );



CREATE TABLE K8S_CLUSTER
(
    K8S_CLUSTER_ID       BIGINT AUTO_INCREMENT COMMENT '',
    NAME                 VARCHAR(100) NOT NULL COMMENT '',
    CONFIG               LONGTEXT NULL COMMENT '',
    PROJECT_ID           BIGINT NOT NULL COMMENT '',
    LAST_CLUSTER_SCAN_ID BIGINT NULL COMMENT '',
    REGISTER_USER_ID     BIGINT NOT NULL COMMENT '',
    REGISTER_USER_LOGIN_ID VARCHAR(100) NOT NULL COMMENT '',
    REGISTER_DATETIME    DATETIME NOT NULL COMMENT '',
    MODIFY_USER_ID       BIGINT NULL COMMENT '',
    MODIFY_USER_LOGIN_ID VARCHAR(100) NULL COMMENT '',
    MODIFY_DATETIME      DATETIME NULL COMMENT '',
    PRIMARY KEY (K8S_CLUSTER_ID)
);



CREATE TABLE MIDDLEWARE_APPLICATION_LINK
(
    APPLICATION_PROCESS_ID BIGINT NOT NULL COMMENT '',
    MIDDLEWARE_PROCESS_ID BIGINT NOT NULL COMMENT '',
    PRIMARY KEY (APPLICATION_PROCESS_ID,MIDDLEWARE_PROCESS_ID)
);



CREATE INDEX _MIDDLEWARE_APPLICATION_LINK_2 ON MIDDLEWARE_APPLICATION_LINK
    (
     APPLICATION_PROCESS_ID
        );



CREATE INDEX _MIDDLEWARE_APPLICATION_LINK_3 ON MIDDLEWARE_APPLICATION_LINK
    (
     MIDDLEWARE_PROCESS_ID
        );



CREATE TABLE MIDDLEWARE_CONFIG
(
    MIDDLEWARE_CONFIG_ID BIGINT AUTO_INCREMENT COMMENT '',
    FILE_PATH            VARCHAR(500) NULL COMMENT '',
    FILE_CONTENT         LONGTEXT NULL COMMENT '',
    PROCESS_ID           BIGINT NOT NULL COMMENT '',
    PRIMARY KEY (MIDDLEWARE_CONFIG_ID)
);



CREATE INDEX _MIDDLEWARE_CONFIG_1 ON MIDDLEWARE_CONFIG
    (
     PROCESS_ID
        );



CREATE TABLE NAMESPACE
(
    NAMESPACE_ID         BIGINT AUTO_INCREMENT COMMENT '',
    NAME                 VARCHAR(100) NOT NULL COMMENT '',
    CLUSTER_SCAN_ID      BIGINT NOT NULL COMMENT '',
    PRIMARY KEY (NAMESPACE_ID)
);



CREATE INDEX _NAMESPACE_1 ON NAMESPACE
    (
     CLUSTER_SCAN_ID
        );



CREATE TABLE NAMESPACE_OBJECT_LINK
(
    NAMESPACE_ID         BIGINT NOT NULL COMMENT '',
    OBJECT_ID            BIGINT NOT NULL COMMENT '',
    PRIMARY KEY (NAMESPACE_ID,OBJECT_ID)
);



CREATE INDEX _NAMESPACE_OBJECT_LINK_1 ON NAMESPACE_OBJECT_LINK
    (
     NAMESPACE_ID
        );



CREATE INDEX _NAMESPACE_OBJECT_LINK_2 ON NAMESPACE_OBJECT_LINK
    (
     OBJECT_ID
        );



CREATE TABLE NODE
(
    NODE_ID              BIGINT AUTO_INCREMENT COMMENT '',
    NAME                 VARCHAR(100) NOT NULL COMMENT '',
    CLUSTER_SCAN_ID      BIGINT NOT NULL COMMENT '',
    KUBELET_VERSION      VARCHAR(50) NOT NULL COMMENT '',
    EXTERNAL_IP          VARCHAR(50) NULL COMMENT '',
    INTERNAL_IP          VARCHAR(50) NOT NULL COMMENT '',
    PRIMARY KEY (NODE_ID)
);



CREATE INDEX _NODE_1 ON NODE
    (
     CLUSTER_SCAN_ID
        );



CREATE TABLE NODE_ANNOTATION
(
    NODE_ANNOTATION_ID   BIGINT AUTO_INCREMENT COMMENT '',
    NAME                 VARCHAR(100) NOT NULL COMMENT '',
    VALUE                VARCHAR(100) NOT NULL COMMENT '',
    NODE_ID              BIGINT NOT NULL COMMENT ''
    ,
    PRIMARY KEY (NODE_ANNOTATION_ID)
);



CREATE INDEX _NODE_ANNOTATION_1 ON NODE_ANNOTATION
    (
     NODE_ID
        );



CREATE TABLE NODE_LABEL
(
    NODE_LABEL_ID        BIGINT AUTO_INCREMENT COMMENT '',
    NAME                 VARCHAR(100) NOT NULL COMMENT '',
    VALUE                VARCHAR(100) NOT NULL COMMENT '',
    NODE_ID              BIGINT NOT NULL COMMENT '',
    PRIMARY KEY (NODE_LABEL_ID)
);



CREATE INDEX _NODE_LABEL_1 ON NODE_LABEL
    (
     NODE_ID
        );



CREATE TABLE OBJECT
(
    OBJECT_ID            BIGINT AUTO_INCREMENT COMMENT '',
    KIND                 VARCHAR(50) NULL COMMENT '',
    NAME                 VARCHAR(100) NOT NULL COMMENT '',
    UID                  VARCHAR(50) NULL COMMENT '',
    CLUSTER_SCAN_ID      BIGINT NOT NULL COMMENT '',
    PARENT_OBJECT_ID     BIGINT NULL COMMENT '',
    PRIMARY KEY (OBJECT_ID)
);



CREATE INDEX _OBJECT_1 ON OBJECT
    (
     CLUSTER_SCAN_ID
        );



CREATE INDEX _OBJECT_2 ON OBJECT
    (
     OBJECT_ID
        );



CREATE TABLE OBJECT_ANNOTATION
(
    OBJECT_ANNOTATION_ID BIGINT AUTO_INCREMENT COMMENT '',
    NAME                 VARCHAR(500) NULL COMMENT '',
    VALUE                LONGTEXT NULL COMMENT '',
    OBJECT_ID            BIGINT NOT NULL COMMENT ''
    ,
    PRIMARY KEY (OBJECT_ANNOTATION_ID)
);



CREATE INDEX _OBJECT_ANNOTATION_1 ON OBJECT_ANNOTATION
    (
     OBJECT_ID
        );



CREATE TABLE OBJECT_LABEL
(
    OBJECT_LABLE_ID      BIGINT AUTO_INCREMENT COMMENT '',
    NAME                 VARCHAR(50) NULL COMMENT '',
    VALUE                VARCHAR(50) NULL COMMENT '',
    OBJECT_ID            BIGINT NOT NULL COMMENT ''
    ,
    PRIMARY KEY (OBJECT_LABLE_ID)
);



CREATE INDEX _OBJECT_LABEL_1 ON OBJECT_LABEL
    (
     OBJECT_ID
        );



CREATE TABLE OBJECT_ORIGIN_JSON
(
    OBJECT_ID            BIGINT NOT NULL COMMENT '',
    JSON                 LONGTEXT NULL COMMENT '',
    PRIMARY KEY (OBJECT_ID)
);



CREATE UNIQUE INDEX _OBJECT_ORIGIN_JSON_1 ON OBJECT_ORIGIN_JSON
    (
     OBJECT_ID
        );



CREATE TABLE POD
(
    OBJECT_ID            BIGINT NOT NULL COMMENT '',
    CLUSTER_IP           VARCHAR(50) NULL COMMENT '',
    NODE_ID              BIGINT NOT NULL COMMENT '',
    PRIMARY KEY (OBJECT_ID)
);



CREATE UNIQUE INDEX _POD_3 ON POD
    (
     OBJECT_ID
        );



CREATE INDEX _POD_4 ON POD
    (
     NODE_ID
        );



CREATE TABLE POD_VOLUME
(
    POD_VOLUME_ID        BIGINT AUTO_INCREMENT COMMENT '',
    NAME                 VARCHAR(100) NOT NULL COMMENT '',
    OBJECT_ID            BIGINT NOT NULL COMMENT '',
    PRIMARY KEY (POD_VOLUME_ID)
);



CREATE INDEX _POD_VOLUME_1 ON POD_VOLUME
    (
     OBJECT_ID
        );



CREATE TABLE PROCESS_EXTERNAL_CONNECT
(
    PROCESS_EXTERNAL_CONNECT_ID BIGINT AUTO_INCREMENT COMMENT '',
    PATH                 VARCHAR(500) NULL COMMENT '',
    PROCESS_ID           BIGINT NOT NULL COMMENT ''
    ,
    PRIMARY KEY (PROCESS_EXTERNAL_CONNECT_ID)
);



CREATE INDEX _PROCESS_EXTERNAL_CONNECT_1 ON PROCESS_EXTERNAL_CONNECT
    (
     PROCESS_ID
        );



CREATE TABLE PROCESS_SERVICE_LINK
(
    PROCESS_SERVICE_LINK_ID BIGINT AUTO_INCREMENT COMMENT '',
    PROCESS_ID           BIGINT NOT NULL COMMENT '',
    OBJECT_ID            BIGINT NULL COMMENT ''
    ,
    PRIMARY KEY (PROCESS_SERVICE_LINK_ID)
);



CREATE INDEX _PROCESS_SERVICE_LINK_2 ON PROCESS_SERVICE_LINK
    (
     OBJECT_ID
        );



CREATE INDEX _PROCESS_SERVICE_LINK_3 ON PROCESS_SERVICE_LINK
    (
     PROCESS_ID
        );



CREATE TABLE SCAN_ORIGIN
(
    SCAN_ORIGIN_ID       BIGINT AUTO_INCREMENT COMMENT '',
    ORIGIN_DATA          LONGTEXT NULL COMMENT '',
    COMMAND_KEY          VARCHAR(50) NULL COMMENT '',
    CLUSTER_SCAN_ID      BIGINT NOT NULL COMMENT '',
    PRIMARY KEY (SCAN_ORIGIN_ID)
);



CREATE INDEX _SCAN_ORIGIN_1 ON SCAN_ORIGIN
    (
     CLUSTER_SCAN_ID
        );



CREATE TABLE SELECTOR
(
    SELECTOR_ID          BIGINT AUTO_INCREMENT COMMENT '',
    NAME                 VARCHAR(50) NULL COMMENT '',
    VALUE                VARCHAR(50) NULL COMMENT '',
    OBJECT_ID            BIGINT NOT NULL COMMENT '',
    PRIMARY KEY (SELECTOR_ID)
);



CREATE INDEX _SELECTOR_1 ON SELECTOR
    (
     OBJECT_ID
        );



CREATE TABLE SERVICE
(
    OBJECT_ID            BIGINT NOT NULL COMMENT '',
    CLUSTER_IP           VARCHAR(50) NULL COMMENT '',
    TYPE                 VARCHAR(50) NULL COMMENT '',
    NAME                 VARCHAR(100) NOT NULL COMMENT '',
    PRIMARY KEY (OBJECT_ID)
);



CREATE UNIQUE INDEX _SERVICE_1 ON SERVICE
    (
     OBJECT_ID
        );



CREATE TABLE SERVICE_PORT
(
    SERVICE_PORT_ID      BIGINT AUTO_INCREMENT COMMENT '',
    NAME                 VARCHAR(100) NULL COMMENT '',
    NODEPORT             INTEGER NULL COMMENT '',
    PORT                 INTEGER NULL COMMENT '',
    PROTOCOL             VARCHAR(50) NULL COMMENT '',
    TARGET_PORT          VARCHAR(50) NULL COMMENT '',
    OBJECT_ID            BIGINT NOT NULL COMMENT '',
    PRIMARY KEY (SERVICE_PORT_ID)
);



CREATE INDEX _SERVICE_PORT_1 ON SERVICE_PORT
    (
     OBJECT_ID
        );


